### ISSUE TITLE
RangeError for toString('utf8') on Nodejs 8.6.0

### ISSUE THREAD

**Issue by dirkschulze** [creationix/jsonparse#37]
I see the following error for Node.js 8.6.0:

```
jsonparse.js:94
    this.string += this.stringBuffer.toString('utf8');
                                     ^

RangeError: Invalid string length
    at Parser.proto.appendStringChar (jsonparse.js:94:38)
    at Parser.proto.write (jsonparse.js:197:34)
```
This does not happen with later versions of Node.js it seems but because of constrains I have to use this particular version.

Is there a workaround for this issue that I could use?

**Comment by Miguel2222222** [comment]
Hi @dirkschulze ,
I am currently getting the same error you mentioned. Could you please let me know if you finally got any solution for this RangeError for toString('utf8') problem? We currently have the same node.js version installed.
Thank you in advance,
Miguel
